### ISSUE TITLE
Can you tell me how to install in English please?

### ISSUE THREAD

**Issue by GGWPXXXX** [wisnshaftler/google-form-automator#1]

**Comment by wisnshaftler** [comment]
follow this video link https://www.youtube.com/watch?v=6l9r4-XrY24

**Comment by GGWPXXXX** [comment]
The Answer That it selected in google form if it's a test, will it choose the correct answer or just random.

**Comment by wisnshaftler** [comment]
nah. we can give correct answers . then this code repeat it again and again. otherwise we can let code to get answer as random.
